<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: 'Courier New', Courier, monospace;
            padding: 20px;
        }

        .container {
            border: 1px solid #333;
            padding: 20px;
            max-width: 600px;
            margin: 0 auto;
        }

        .alert-box {
            padding: 15px;
            text-align: center;
            border: 2px solid;
            margin-bottom: 20px;
            font-weight: bold;
        }

        .red-mode {
            border-color: #ff0000;
            color: #ff0000;
            background-color: #1a0000;
        }

        .green-mode {
            border-color: #00ff00;
            color: #00ff00;
            background-color: #001a00;
        }

        .message {
            margin-top: 20px;
            line-height: 1.5;
            color: #777C6D;
        }

        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #555;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="container">
        @if ($isMaintenance)
            <div class="alert-box red-mode">
                [ SYSTEM LOCKDOWN INITIATED ]<br>
                ACCESS RESTRICTED
            </div>
            <h2 style="color: #ff0000;">PERHATIAN SELURUH AGENT,</h2>
            <div class="message">
                BlackFile saat ini memasuki mode <strong>MAINTENANCE DARURAT</strong>.
                <br><br>
                Akses ke dalam sistem ditutup sementara untuk perbaikan infrastruktur keamanan.
                Jangan mencoba menerobos masuk (Brute Force) atau IP Anda akan di-blacklist permanen.
                <br><br>
                Status: <span style="color: red;">OFFLINE</span>
            </div>
        @else
            <div class="alert-box green-mode">
                [ SYSTEM ONLINE ]<br>
                ACCESS GRANTED
            </div>
            <h2 style="color: #00ff00;">SISTEM TELAH PULIH,</h2>
            <div class="message">
                Proses maintenance telah selesai. Jaringan BlackFile kembali stabil.
                Anda diperbolehkan untuk login kembali dan melanjutkan operasi.
                <br><br>
                Status: <span style="color: #00ff00;">OPERATIONAL</span>
            </div>
        @endif

        <div class="footer">
            MESSAGE GENERATED BY BLACKFILE COMMAND CENTER<br>
            {{ now()->format('Y-m-d H:i:s') }} UTC
        </div>
    </div>
</body>

</html>
