<div class="bg-surface border border-border-color rounded-lg p-4">
    <div
        class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4 border-b border-border-color pb-2 gap-2">
        <p class="text-sm sm:text-xl font-bold text-white">> INVITE TOKENS</p>
        <form action="{{ route('admin.invites.generate') }}" method="POST" class="w-full sm:w-auto">
            @csrf
            <x-button type="submit" class="w-full sm:w-auto">
                [ + GENERATE TOKEN ]
            </x-button>
        </form>
    </div>
    <div class="space-y-3 max-h-96 overflow-y-auto pr-2">
        @forelse($invites as $invite)
            <div class="bg-base p-3 rounded-md" x-data="{ copied: false }">
                <div class="flex items-center justify-between gap-4">
                    <p class="font-mono text-primary-hover break-all" x-ref="token_{{ $invite->id }}">
                        {{ $invite->code }}</p>
                    <button
                        @click="
                        navigator.clipboard.writeText($refs.token_{{ $invite->id }}.innerText);
                        copied = true;
                        setTimeout(() => { copied = false }, 2000);
                    "
                        class="px-3 py-1 text-xs font-bold rounded transition-colors flex-shrink-0"
                        :class="copied ? 'bg-green-600 text-white' :
                            'bg-secondary/20 text-secondary hover:bg-secondary/40'">
                        <span x-show="!copied">[ COPY ]</span>
                        <span x-show="copied">COPIED!</span>
                    </button>
                </div>
                <div class="text-xs text-secondary mt-1 flex justify-between">
                    <span>Generated by: {{ $invite->creator->codename }}</span>
                    @if ($invite->used)
                        <span class="text-red-500">USED</span>
                    @elseif($invite->expires_at && $invite->expires_at->isPast())
                        <span class="text-yellow-500">EXPIRED</span>
                    @else
                        <span class="text-green-500">AVAILABLE</span>
                    @endif
                </div>
            </div>
        @empty
            <p class="text-secondary text-center p-4">[ NO INVITE TOKENS GENERATED ]</p>
        @endforelse
    </div>
</div>
